name: password_master
description: "An application that helps you generate and manage passwords."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.6.2

dependencies:
  adaptive_theme: 3.7.0
  auto_route: 9.3.0+1
  bot_toast: 4.1.3
  collection: 1.19.0
  cupertino_icons: 1.0.8
  dartx: 1.2.0
  easy_localization: 3.0.7+1
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 9.2.4
  fpdart: 1.1.1
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  riverpod_annotation: 2.6.1
  shared_preferences: 2.5.1
  talker_dio_logger: 4.6.10
  talker_flutter: 4.6.10
  talker_riverpod_logger: 4.6.10

dev_dependencies:
  auto_route_generator: 9.3.1
  build_runner: 2.4.14
  custom_lint: 0.7.2
  flutter_gen_runner: 5.9.0
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  json_serializable: 6.9.3
  riverpod_generator: 2.6.4
  riverpod_lint: 2.6.4

flutter_gen:
  output: lib/core/gen

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      - assets/i18n/*

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
