name: password_master
description: "An application that helps you generate and manage passwords."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  adaptive_theme: 3.6.0
  auto_route: 7.9.2
  bot_toast: 4.1.3
  cupertino_icons: 1.0.6
  dartx: 1.2.0
  easy_localization: 3.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_screenutil: 5.9.0
  fpdart: 1.1.0
  freezed_annotation: 2.4.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  json_annotation: 4.8.1
  modal_bottom_sheet: 3.0.0
  riverpod_annotation: 2.3.5

dev_dependencies:
  auto_route_generator: 7.3.2
  build_runner: 2.4.8
  custom_lint: 0.6.4
  flutter_gen_runner: 5.4.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  hive_generator: 2.0.1
  json_serializable: 6.7.1
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10

flutter_gen:
  output: lib/core/gen

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      - assets/i18n/*

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
